export const ADD_TODO_REQUEST='ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL='ADD_TODO_FAIL'

export const ADD_USER_REQUEST='ADD_USER_REQUEST'
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS'
export const ADD_USER_FAIL='ADD_USER_FAIL'

export const REMOVE_TODO_REQUEST='REMOVE_TODO_REQUEST'
export const REMOVE_TODO_SUCCESS='REMOVE_TODO_SUCCESS'
export const REMOVE_TODO_RESET='REMOVE_TODO_RESET'
export const REMOVE_TODO_FAIL='REMOVE_TODO_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'